
tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 8000
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker